### ISSUE TITLE
banned after upgrade till 1.3.1

### ISSUE THREAD

**Issue by magmel48** [ArkEcosystem/ark-node#120] opened 2018-10-14 07:48 UTC
I used mainnet and in logs I had:

[inf] 2018-10-12 10:10:25 | http://5.39.53.54:4001 banned for 360 minutes
[inf] 2018-10-12 10:10:25 | http://5.39.53.55:4001 banned for 360 minutes
[inf] 2018-10-12 10:10:25 | http://37.59.129.160:4001 banned for 360 minutes
[inf] 2018-10-12 10:10:25 | http://37.59.129.161:4001 banned for 360 minutes
[inf] 2018-10-12 10:10:25 | http://37.59.129.162:4001 banned for 360 minutes
[inf] 2018-10-12 10:10:25 | http://37.59.129.163:4001 banned for 360 minutes
[inf] 2018-10-12 10:10:25 | http://37.59.129.164:4001 banned for 360 minutes
[inf] 2018-10-12 10:10:25 | http://37.59.129.165:4001 banned for 360 minutes
[inf] 2018-10-12 10:10:25 | http://37.59.129.166:4001 banned for 360 minutes
[inf] 2018-10-12 10:10:25 | http://37.59.129.167:4001 banned for 360 minutes
[inf] 2018-10-12 10:10:25 | http://37.59.129.168:4001 banned for 360 minutes
[inf] 2018-10-12 10:11:25 | http://5.39.53.51:4001 banned for 360 minutes
...

because of that I could not receive incoming payments and my node was out of sync for long time. It happened right after I updated my node till 1.3.1 on this Saturday.

**Comment by faustbrian** [comment] 2018-10-14 07:52
Have you updated to 1.3.2 and tried again if the issue is resolved?

**Comment by magmel48** [comment] 2018-10-14 07:53
this repo doesn't have 1.3.2 version

**Comment by faustbrian** [comment] 2018-10-14 07:54
It does https://github.com/ArkEcosystem/ark-node/blob/mainnet/config.mainnet.json#L4. Use ARKcommander and hit 3 to update or pull via git.

**Comment by magmel48** [comment] 2018-10-14 07:55
please create tag then. https://github.com/ArkEcosystem/ark-node/releases/tag/1.3.1 is latest in releases section

**Comment by faustbrian** [comment] 2018-10-14 07:57
Should be tagged now but you can simply pull in the `mainnet` branch in general.

**Comment by magmel48** [comment] 2018-10-14 13:17
thank you!

**Comment by faustbrian** [comment] 2018-10-21 06:11
Closing this as no further response was received. If the issue continues to exist feel free to reopen it.

**Closed as completed by faustbrian** 2018-10-21 06:11 UTC
